create table if not exists cliente (
  id integer generated by default as identity primary key,
  nome varchar(150) not null,
  cpf_cnpj varchar(18),
  email varchar(150),
  telefone varchar(20),
  ativo char(1) not null default 'S' check (ativo in ('S','N')),
  data_cadastro timestamp not null default current_timestamp,
  data_atualizacao timestamp
);

create unique index if not exists uq_cliente_cpf_cnpj on cliente(cpf_cnpj) where cpf_cnpj is not null;

create table if not exists produto (
  id integer generated by default as identity primary key,
  codigo varchar(30) not null unique,
  descricao varchar(150) not null,
  preco numeric(15,2) not null default 0 check (preco >= 0),
  ativo char(1) not null default 'S' check (ativo in ('S','N')),
  data_cadastro timestamp not null default current_timestamp,
  data_atualizacao timestamp
);

create table if not exists venda (
  id integer generated by default as identity primary key,
  cliente_id integer not null references cliente(id),
  data_venda timestamp not null default current_timestamp,
  valor_total numeric(15,2) not null default 0 check (valor_total >= 0),
  status varchar(20) not null default 'PENDENTE'
    check (status in ('PENDENTE','QUITADA','CANCELADA')),
  observacao varchar(500)
);

create table if not exists venda_item (
  id integer generated by default as identity primary key,
  venda_id integer not null references venda(id) on delete cascade,
  produto_id integer not null references produto(id),
  quantidade numeric(15,3) not null check (quantidade > 0),
  valor_unitario numeric(15,2) not null check (valor_unitario >= 0),
  valor_total numeric(15,2) not null check (valor_total >= 0)
);

create table if not exists financeiro (
  id integer generated by default as identity primary key,
  venda_id integer not null unique references venda(id),
  valor numeric(15,2) not null default 0,
  status varchar(20) not null default 'PENDENTE',
  data_vencimento date,
  data_quitacao timestamp,
  data_cancelamento timestamp,
  motivo_cancelamento varchar(500),
  data_cadastro timestamp not null default current_timestamp,
  data_atualizacao timestamp
);

insert into cliente(nome, cpf_cnpj, email, telefone)
select 'Cliente Teste','00000000000','teste@catsys.local','00000000000'
where not exists (select 1 from cliente where cpf_cnpj='00000000000');

insert into produto(codigo, descricao, preco)
select 'TESTE-001','Produto Teste',100.00
where not exists (select 1 from produto where codigo='TESTE-001');
